apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: rhods-trustyai-service-operator
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: trustyai-service-operator
    name: trustyai-service-operator
  repos:
  - name: manifests
    uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
